{
 "title": "Nginx Ingress Scale Test",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Echo CPU by Pod (Usage / Requested)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(container_cpu_usage_seconds_total{image!=\"\", container=~\"echo\"}[3m])) by (pod) * 100 / sum(kube_pod_container_resource_requests_cpu_cores{container=~\"echo\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingress CPU By Pod (Usage / Requested)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(container_cpu_usage_seconds_total{image!=\"\", container=~\"controller\"}[3m])) by (pod) * 100 / sum(kube_pod_container_resource_requests_cpu_cores{container=~\"controller\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingress RPS By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_requests_total [1m])",
     "legendFormat": "{{controller_pod}}"
    }
   ]
  },
  {
   "title": "Ingress RPS Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"[4-5].*\"} [2m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}