{
 "title": "Kong Ingress Scale Test",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Echo CPU by Pod (Usage / Requested)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(container_cpu_usage_seconds_total{image!=\"\", container=~\"echo\"}[3m])) by (pod) * 100 / sum(kube_pod_container_resource_requests_cpu_cores{container=~\"echo\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingress CPU By Pod (Usage / Requested)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(container_cpu_usage_seconds_total{image!=\"\", container=~\"proxy\"}[3m])) by (pod) * 100 / sum(kube_pod_container_resource_requests_cpu_cores{container=~\"proxy\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ingress RPS By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_status [1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Ingress RPS Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_status{code=~\"[4-5].*\"} [2m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Ingress Waiting Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kong_nginx_http_current_connections{state=\"waiting\"})",
     "legendFormat": "Waiting"
    }
   ]
  }
 ]
}