{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_cpu:rate:sum)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores)",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total Cores" }
   ]
  },
  {
   "title": "Memory Usage(Gb)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)/(1024*1024*1024))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)/(1024*1024*1024)",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes)/(1024*1024*1024)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes)/(1024*1024*1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods) - sum(kube_pod_info)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_pod_info{created_by_kind=~\"DaemonSet\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_info{created_by_kind!~\"DaemonSet\"})",
     "legendFormat": "DeamonSet"
    }
   ]
  },
  {
   "title": "Containers CPU Usage(Top 5)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[3m])) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Top CPU Reserved",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(kube_pod_container_resource_requests_cpu_cores) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Limit/Requested",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(kube_pod_container_resource_limits_cpu_cores) by (container) * 100 / sum(kube_pod_container_resource_requests_cpu_cores) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Containers CPU Usage/Requested(Top 5)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[3m])) by (container) * 100 / sum(kube_pod_container_resource_requests_cpu_cores) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Node $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "node" },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{node=~\"$node\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$node\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{node=~\"$node\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Memory Usage(Gb)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{node=~\"$node\"} - node_memory_MemAvailable_bytes{node=~\"$node\"})/(1024*1024*1024)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})/(1024*1024*1024)",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$node\"})/(1024*1024*1024)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=~\"$node\"})/(1024*1024*1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"}) - sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_pod_info{created_by_kind!~\"DaemonSet\", node=~\"$node\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_info{created_by_kind=~\"DaemonSet\", node=~\"$node\"})",
     "legendFormat": "DeamonSets"
    }
   ]
  },
  {
   "title": "Containers CPU Usage(Top 5)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\", node=~\"$node\"}[3m])) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Top CPU Reserved",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers CPU Usage/Requested(Top 5)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\",node=~\"$node\"}[3m])) by (container) * 100 / sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Node $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{node=~\"$node\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"$node\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{node=~\"$node\"})",
     "legendFormat": "Total Cores"
    }
   ]
  },
  {
   "title": "Memory Usage(Gb)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{node=~\"$node\"} - node_memory_MemAvailable_bytes{node=~\"$node\"})/(1024*1024*1024)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})/(1024*1024*1024)",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"$node\"})/(1024*1024*1024)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=~\"$node\"})/(1024*1024*1024)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"}) - sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_pod_info{created_by_kind!~\"DaemonSet\", node=~\"$node\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_info{created_by_kind=~\"DaemonSet\", node=~\"$node\"})",
     "legendFormat": "DeamonSets"
    }
   ]
  },
  {
   "title": "Containers CPU Usage(Top 5)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\", node=~\"$node\"}[3m])) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Top CPU Reserved",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers CPU Usage/Requested(Top 5)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\",node=~\"$node\"}[3m])) by (container) * 100 / sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}