
controller:

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - "ingress-nginx"
          topologyKey: "kubernetes.io/hostname"

  resources:
    limits:
      cpu: "350m"
      memory: "500Mi"
    requests:
      cpu: "350m"
      memory: "256Mi"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"

  service:
    enabled: true

    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      #service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'

  extraArgs:
    metrics-per-host: "false"

  metrics:
    port: 10254
    # if this port is changed, change healthz-port: in extraArgs: accordingly
    enabled: true

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
